### PR TITLE
doc: Add a README giving context for this repository

### PR DESCRIPTION
**Pull request by Hurricos**
Signed-off-by: Martin Kennedy <hurricos@gmail.com>

### CODE REVIEW

**Comment by Hurricos** [comment]
Should have SoB in the commit, but whatever. This isn't OpenWrt.

**Comment by Hurricos** [comment]
Force-pushed some footnotes fixes. [Footnotes in Markdown are hard](https://github.com/Hurricos/realtek-registers/tree/add-readme)!

*Now* it's ready for review.

**Comment by Hurricos** [comment]
Removed some unwanted links.

**Comment by svanheule** [comment]
Thanks! I did drop the Footnotes section, which became empty with the last revision, but otherwise no changes.

**Pull request closed without merging**
