### PR TITLE
Functional style changes

### PR DESCRIPTION
**Pull request by biot**
Nothing shocking, just improving readability. Making it pretty is for somebody else.

### CODE REVIEW

**Comment by svanheule** [comment]
Could you rebase and split the patch into "data display" and "style" changes?

**Comment by svanheule** [comment]
I've merged the first patch, and parts of the second patch:
- Fix table row closing tags (69e84997dad035b3716a7fd2ef69e4491c2d4e79)
- Alternating colours for table row backgrounds, left align tables (b430c0d3223b683af2cd316f18ca971f144c4cde)

I will have another look later at how to group the table rows by feature.

**Comment by svanheule** [comment]
Concerning the non-repeating feature names, how does this look to you:
image

**Comment by biot** [comment]
Looks great, the line is an improvement. However if you put the feature on a line by itself as I did, its column doesn't have to be so wide, which lets you arrange the columns better.

**Comment by svanheule** [comment]
Grouping registers by feature was also added (6311834d01e39cc1890c2609cbb06e1aa6b6d3c5), so I think that resolves all the issues addressed here.

**Pull request closed without merging**
